### ISSUE TITLE
Devise::Models::Trackable#update_tracked_fields! using wrong save method

### ISSUE THREAD

**Issue by mbrock** [NoBrainerORM/devise-nobrainer#2]
See [this line](https://github.com/plataformatec/devise/blob/710efe557d38a897474ef27c051384d5edee26fc/lib/devise/models/trackable.rb#L33) in Devise.

Since NoBrainer's `save` method always returns `nil`, the trackable module always raises an exception.

I'm not sure how or where to solve this. Devise uses the `orm_adapter` gem, but that gem intentionally does not try to unify model instance methods like `save`.

I tried monkey-patching the `update_tracked_fields!` method from my own code, but couldn't figure out how to change this already-mixed-in method.

**Comment by nviennot** [comment]
See https://github.com/plataformatec/devise/pull/3411 for progress.

Another issue is with https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L81 which won't call your `after_confirmation` callbacks.
