### ISSUE TITLE
Password change in devise does not work

### ISSUE THREAD

**Issue by samuelebistoletti** [NoBrainerORM/devise-nobrainer#3]
After resetting password (forgot password path provided by devise), opened the link provided in the email, it is not possible to set a new password anymore. When I try to submit the form with the new password chosen an exception is raised as you can seee on the attached stacktrace.

Tests have been made using Ruby 2.2.0, Rails 4.2 with Devise 3.4.1 and No Brainer 0.21.0 with Devise No Brainer at 0.5.0.

![screenshot from 2015-03-06 12 03 36](https://cloud.githubusercontent.com/assets/4482391/6524478/293ebc00-c3fa-11e4-87af-0a3417ee694c.png)

**Comment by nviennot** [comment]
That should be fixed in nobrainer master: https://github.com/nviennot/nobrainer/commit/039e119219aa4a2c5d54c32d604f2ab9e6e7f683

I'll release a new version soon :)
