### ISSUE TITLE
Trackable module in Devise does not work

### ISSUE THREAD

**Issue by samuelebistoletti** [NoBrainerORM/devise-nobrainer#4]
As you can see from the attached screenshot an exception is raised when I try to login with my account using Devise and trackable module is enabled (by default when Devise is installed). It is not clear if the problem is directly related with No Brainer ORM.

Tests have been made using Ruby 2.2.0, Rails 4.2 with Devise 3.4.1 and No Brainer 0.21.0 with Devise No Brainer at 0.5.0.

![screenshot from 2015-03-06 12 16 56](https://cloud.githubusercontent.com/assets/4482391/6524613/eb898a32-c3fb-11e4-9072-a1af7d725056.png)

**Comment by nviennot** [comment]
This is the problem of `save` vs `save!`. I fixed that in devise though: https://github.com/plataformatec/devise/pull/3411

Use devise from their master branch since they haven't released a new version yet.

edit: fix link

**Comment by samuelebistoletti** [comment]
ok thank you for your suggestions ;)
