### ISSUE TITLE
Rails 4 and update_without_password

### ISSUE THREAD

**Issue by alolis** [NoBrainerORM/devise-nobrainer#5]
Hello,

I am trying to update a few model attributes with the use of model.update_without_password but unfortunately it does not work. Has anyone had a similar problem?

Is this gem even maintained at this point?

Thank you for your time

**Comment by nviennot** [comment]
update_without_password is a Devise method, so plug in Devise.

> Is this gem even maintained at this point?

Not sure what you are referring to with "at this point", but yes, NoBrainer is maintained.

**Comment by alolis** [comment]
@nviennot , thanks for getting back to me.

Yes, i am aware that it's a devise method but since this gem (devise-nobrainer) is the glue for all this I asked here. I am trying to figure out the issue.

I meant if devise-nobrainer is maintained since I saw that last commit was 10 months ago.

**Comment by nviennot** [comment]
I tried the `update_without_password` and I had to add `update_attributes()` back: https://github.com/nviennot/nobrainer/commit/dfe881df4e5239e68a7e203b448e5d19e06af4b5

If you use nobrainer from master, you should be able to get it to work.
Next time, try to include a stack trace or something, it would have been way easier ;)
