### ISSUE TITLE
Fatal: The model `User' is already registered and partially loaded.

### ISSUE THREAD

**Issue by abuisman** [NoBrainerORM/devise-nobrainer#6]
Hi,

With Rails 5, Devise 4.2 and devise-nobrainer 0.5.0 I get the following error quite often:

```
Fatal: The model `User' is already registered and partially loaded. This may happen when an exception occured while loading the model definitions (e.g. calling a missing class method on another model, having circular dependencies). In this situation, ActiveSupport autoloader may retry loading the model. Try moving all class methods declaration at the top of the model.
```

This usually happens every time I change controller and model code. The line the error is thrown at is:

![image](https://cloud.githubusercontent.com/assets/27729/16997175/a3c98ab8-4eb4-11e6-8551-07d87ff3590f.png)

I am sure I am just one config change away, but I have no idea where to begin. Any advice?

**Comment by nviennot** [comment]
If you can install https://tmate.io/ and share a terminal with me (share the link via an email), I can come in and help out to see what's going on

**Comment by abuisman** [comment]
@nviennot that sounds great. I'll get in touch through e-mail. 

In the meantime I noticed that I forgot to mention that when I get this error and reboot the server everything works again until the next time I change a model or controller.

**Comment by nviennot** [comment]
I won't be available until tomorrow afternoon, so if you just share the sources, that's cool too.
I just need a way to reproduce the bug.

**Comment by abuisman** [comment]
@nviennot I whipped up a project with, what I hope, are the minimum requirements for reproducing the error:

https://github.com/abuisman/reproduce-nobrainer-devise-bug

Steps to reproduce:
1. run the server
2. open the root url in the browser
3. edit the User model (e.g. move the timestamps line from top to bottom or reverse)
4. reload the root url in the browser

If all goes... well, badly, you should see the error I am getting. When you stop the server, restart it and then reload the page again the error is gone, until you edit certain files again.

Hope you get a chance to check it out.

**Comment by nviennot** [comment]
https://github.com/nviennot/nobrainer/commit/483972a12b6f90cb0888c972ba923d456c68a580

that should fix the issue

Thanks for the bug report :)

**Comment by abuisman** [comment]
@nviennot thanks for having a look!

Are you making a new release any time soon or should I ref the git repo in the Gemfile for now?

Edit:

Works perfectly btw :)

**Comment by nviennot** [comment]
I'll make a new release by the end of the month.
You can use the git repo in the gemfile for now.

**Comment by abuisman** [comment]
Cool. Thanks again.
